// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApp.DAL.Data;

#nullable disable

namespace RestaurantApp.DAL.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Name = "Classic Burger",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = 5,
                            Name = "Caesar Salad",
                            Price = 9.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = 4,
                            Name = "Coca-Cola",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = 7,
                            Name = "Fries",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 5,
                            Category = 3,
                            Name = "Chocolate Lava Cake",
                            Price = 7.50m
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Name = "Spaghetti Bolognese",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = 4,
                            Name = "Orange Juice",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Name = "Chicken Wings (6 pcs)",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Name = "Cheesecake",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            Name = "Vegetable Pizza",
                            Price = 14.00m
                        });
                });

            modelBuilder.Entity("Restaurant.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 20.00m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 7, 3, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 19.00m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 7, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 22.50m
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 7, 7, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 24.50m
                        });
                });

            modelBuilder.Entity("Restaurant.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            MenuItemId = 1,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            Count = 1,
                            MenuItemId = 4,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Count = 1,
                            MenuItemId = 3,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Count = 1,
                            MenuItemId = 2,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 5,
                            Count = 1,
                            MenuItemId = 8,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Count = 1,
                            MenuItemId = 6,
                            OrderId = 3
                        },
                        new
                        {
                            Id = 7,
                            Count = 1,
                            MenuItemId = 5,
                            OrderId = 3
                        },
                        new
                        {
                            Id = 8,
                            Count = 1,
                            MenuItemId = 10,
                            OrderId = 4
                        },
                        new
                        {
                            Id = 9,
                            Count = 1,
                            MenuItemId = 7,
                            OrderId = 4
                        },
                        new
                        {
                            Id = 10,
                            Count = 1,
                            MenuItemId = 9,
                            OrderId = 4
                        },
                        new
                        {
                            Id = 11,
                            Count = 2,
                            MenuItemId = 3,
                            OrderId = 4
                        });
                });

            modelBuilder.Entity("Restaurant.Core.Models.OrderItem", b =>
                {
                    b.HasOne("Restaurant.Core.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Restaurant.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
